"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import importlib.util
import os

from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _


def env_list(name, default=""):
    raw_value = os.getenv(name, default)
    return [item.strip() for item in raw_value.split(",") if item.strip()]

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-ip2d(a^%_o#d^vf_!vk*p2s-y9$juv4h+hir=kja!newym35h4')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = env_list('ALLOWED_HOSTS', 'localhost,127.0.0.1,testserver')


# Application definition

UNFOLD_INSTALLED = importlib.util.find_spec("unfold") is not None
CORSHEADERS_INSTALLED = importlib.util.find_spec("corsheaders") is not None
WHITENOISE_INSTALLED = importlib.util.find_spec("whitenoise") is not None

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt.token_blacklist',
    'rest_framework_simplejwt',
    'api',
    'discussions',
    'hardware_orch',
    'tutorials',
    'observability.apps.ObservabilityConfig',

    # all auth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',

    # dj - rest auth 
    'dj_rest_auth',
    'dj_rest_auth.registration',
]

if UNFOLD_INSTALLED:
    INSTALLED_APPS.insert(0, "unfold")
if CORSHEADERS_INSTALLED:
    INSTALLED_APPS.insert(8, "corsheaders")

MIDDLEWARE = [
    'allauth.account.middleware.AccountMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'observability.middleware.RequestContextMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if CORSHEADERS_INSTALLED:
    MIDDLEWARE.insert(0, "corsheaders.middleware.CorsMiddleware")
if WHITENOISE_INSTALLED:
    MIDDLEWARE.insert(3, "whitenoise.middleware.WhiteNoiseMiddleware")

REST_AUTH = {
    'USE_JWT': True,
    'LOGIN_SERIALIZER': 'api.auth_serializers.CustomLoginSerializer',
    'JWT_AUTH_COOKIE': 'access-token',
    'JWT_AUTH_REFRESH_COOKIE': 'refresh-token',
    'JWT_AUTH_HTTPONLY': True,
    'JWT_AUTH_SECURE': True,  # Set to True in production (HTTPS)
    'JWT_AUTH_SAMESITE': 'Lax',
    'PASSWORD_RESET_USE_HTMLEMAIL': False,
    'PASSWORD_RESET_SERIALIZER': 'api.auth_serializers.CustomPasswordResetSerializer',
    'REGISTER_SERIALIZER': 'api.auth_serializers.CustomRegisterSerializer',
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

ROOT_URLCONF = 'backend.urls'

CORS_ALLOW_ALL_ORIGINS = os.getenv('CORS_ALLOW_ALL_ORIGINS', 'True') == 'True'
CORS_ALLOWED_ORIGINS = env_list(
    'CORS_ALLOWED_ORIGINS',
    'http://localhost,http://127.0.0.1,http://localhost:5173,http://127.0.0.1:5173'
)
CSRF_TRUSTED_ORIGINS = env_list(
    'CSRF_TRUSTED_ORIGINS',
    'http://localhost,http://127.0.0.1,http://localhost:5173,http://127.0.0.1:5173'
)

SITE_ID = 1

REST_FRAMEWORK = {

    'DEFAULT_AUTHENTICATION_CLASSES': (
        
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

# settings.py
EMAIL_BACKEND = os.getenv(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend'
)
EMAIL_HOST = os.getenv('EMAIL_HOST', 'localhost')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 1025))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'False') == 'True'
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'False') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_TIMEOUT = int(os.getenv('EMAIL_TIMEOUT', 10))
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@sabhuku.local')
SERVER_EMAIL = os.getenv('SERVER_EMAIL', DEFAULT_FROM_EMAIL)

ACCOUNT_EMAIL_VERIFICATION = 'none' # Options: 'mandatory', 'optional', 'none'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
ACCOUNT_USERNAME_REQUIRED = True

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases


if os.environ.get("DB_NAME"):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("DB_NAME"),
            "USER": os.environ.get("DB_USER"),
            "PASSWORD": os.environ.get("DB_PASSWORD"),
            "HOST": os.environ.get("DB_HOST", "127.0.0.1"),
            "PORT": os.environ.get("DB_PORT", "5432"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
if WHITENOISE_INSTALLED:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

if UNFOLD_INSTALLED:
    UNFOLD = {
        "SITE_TITLE": "Sabhuku Admin",
        "SITE_HEADER": "SABHUKU AI",
        "SITE_SUBHEADER": "Operations Console",
        "SITE_URL": "/dashboard",
        "SITE_SYMBOL": "neurology",
        "SHOW_HISTORY": True,
        "SHOW_VIEW_ON_SITE": False,
        "BORDER_RADIUS": "14px",
        "THEME": "light",
        "STYLES": [
            lambda request: static("admin/css/sabhuku-admin.css"),
        ],
        "DASHBOARD_CALLBACK": "observability.dashboard.admin_dashboard_callback",
        "COLORS": {
            "base": {
                "50": "#f8fafc",
                "100": "#f1f5f9",
                "200": "#e2e8f0",
                "300": "#cbd5e1",
                "400": "#94a3b8",
                "500": "#64748b",
                "600": "#475569",
                "700": "#334155",
                "800": "#1e293b",
                "900": "#0f172a",
                "950": "#020617",
            },
            "primary": {
                "50": "#eff6ff",
                "100": "#dbeafe",
                "200": "#bfdbfe",
                "300": "#93c5fd",
                "400": "#60a5fa",
                "500": "#3b82f6",
                "600": "#2563eb",
                "700": "#1d4ed8",
                "800": "#1e40af",
                "900": "#1e3a8a",
                "950": "#172554",
            },
            "font": {
                "subtle-light": "#64748b",
                "default-light": "#334155",
                "important-light": "#0f172a",
            },
        },
        "SIDEBAR": {
            "show_search": True,
            "show_all_applications": False,
            "navigation": [
                {
                    "title": _("Workspace"),
                    "separator": True,
                    "items": [
                        {"title": _("Overview"), "icon": "dashboard", "link": reverse_lazy("admin:index")},
                        {"title": _("Observability"), "icon": "monitoring", "link": reverse_lazy("admin:observability_dashboard")},
                    ],
                },
                {
                    "title": _("Content"),
                    "items": [
                        {"title": _("Models"), "icon": "inventory_2", "link": reverse_lazy("admin:api_model_changelist")},
                        {"title": _("Datasets"), "icon": "database", "link": reverse_lazy("admin:api_dataset_changelist")},
                        {"title": _("Discussions"), "icon": "forum", "link": reverse_lazy("admin:discussions_discussion_changelist")},
                        {"title": _("Community Tutorials"), "icon": "article", "link": reverse_lazy("admin:tutorials_tutorial_changelist")},
                    ],
                },
                {
                    "title": _("System"),
                    "items": [
                        {"title": _("Users"), "icon": "group", "link": reverse_lazy("admin:auth_user_changelist")},
                        {"title": _("Groups"), "icon": "shield", "link": reverse_lazy("admin:auth_group_changelist")},
                        {"title": _("Hardware Profiles"), "icon": "memory", "link": reverse_lazy("admin:hardware_orch_hardwareprofile_changelist")},
                        {"title": _("Model Profiling"), "icon": "tune", "link": reverse_lazy("admin:hardware_orch_modelprofile_changelist")},
                        {"title": _("App Logs"), "icon": "receipt_long", "link": reverse_lazy("admin:observability_applicationlog_changelist")},
                        {"title": _("Event Logs"), "icon": "event_note", "link": reverse_lazy("admin:observability_eventlog_changelist")},
                    ],
                },
            ],
        },
    }

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE', 'False') == 'True'
CSRF_COOKIE_SECURE = os.getenv('CSRF_COOKIE_SECURE', 'False') == 'True'
SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'False') == 'True'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

GS_BUCKET_NAME = os.getenv("GS_BUCKET_NAME", "sabhuku-bucket")
GS_UPLOAD_URL_EXPIRATION_MINUTES = int(os.getenv("GS_UPLOAD_URL_EXPIRATION_MINUTES", "15"))
GS_DOWNLOAD_URL_EXPIRATION_HOURS = int(os.getenv("GS_DOWNLOAD_URL_EXPIRATION_HOURS", "1"))
PUBLIC_SITE_URL = os.getenv("PUBLIC_SITE_URL", "")



LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO")
LOG_DB_LEVEL = os.getenv("LOG_DB_LEVEL", "WARNING")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "request_context": {
            "()": "observability.handlers.RequestContextFilter",
        },
        "stdout_max_level": {
            "()": "observability.handlers.MaxLevelFilter",
            "max_level": "WARNING",
        },
        "stderr_min_level": {
            "()": "observability.handlers.MinLevelFilter",
            "min_level": "ERROR",
        },
    },
    "formatters": {
        "structured": {
            "format": "[{asctime}] {levelname} {name} req={request_id} user={user_id} "
                      "status={status_code} {request_method} {request_path} - {message}",
            "style": "{",
        },
    },
    "handlers": {
        "stdout": {
            "class": "logging.StreamHandler",
            "level": LOG_LEVEL,
            "stream": "ext://sys.stdout",
            "filters": ["request_context", "stdout_max_level"],
            "formatter": "structured",
        },
        "stderr": {
            "class": "logging.StreamHandler",
            "level": "ERROR",
            "stream": "ext://sys.stderr",
            "filters": ["request_context", "stderr_min_level"],
            "formatter": "structured",
        },
        "database": {
            "class": "observability.handlers.DatabaseLogHandler",
            "level": LOG_DB_LEVEL,
            "filters": ["request_context"],
        },
    },
    "root": {
        "handlers": ["stdout", "stderr", "database"],
        "level": LOG_LEVEL,
    },
    "loggers": {
        "django": {
            "handlers": ["stdout", "stderr", "database"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "django.request": {
            "handlers": ["stderr", "database"],
            "level": "ERROR",
            "propagate": False,
        },
        "django.server": {
            "handlers": ["stdout", "stderr"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "gunicorn.error": {
            "handlers": ["stderr", "database"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "gunicorn.access": {
            "handlers": ["stdout"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
    },
}
