# Generated by Django 6.0.4 on 2026-04-17 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModelProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("model_name", models.CharField(blank=True, max_length=255)),
                ("source", models.CharField(max_length=1024)),
                ("source_kind", models.CharField(choices=[("url", "URL"), ("path", "Local path")], max_length=16)),
                (
                    "preferred_optimization",
                    models.CharField(
                        choices=[("cost", "Cost"), ("latency", "Latency"), ("balanced", "Balanced")],
                        default="balanced",
                        max_length=16,
                    ),
                ),
                ("requested_providers", models.JSONField(blank=True, default=list)),
                ("use_spot", models.BooleanField(default=False)),
                ("allow_inferentia", models.BooleanField(default=False)),
                ("profile_summary", models.TextField(blank=True)),
                ("profile_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="HardwareProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider", models.CharField(max_length=32)),
                ("instance_name", models.CharField(max_length=255)),
                ("gpu_model", models.CharField(blank=True, max_length=255)),
                ("gpu_count", models.PositiveIntegerField(default=0)),
                ("total_vram_gb", models.FloatField(default=0.0)),
                ("ram_gb", models.FloatField(default=0.0)),
                ("score", models.FloatField(default=0.0)),
                ("cost_per_hour", models.FloatField(default=0.0)),
                ("vram_headroom", models.FloatField(default=0.0)),
                ("recommendation_data", models.JSONField(blank=True, default=dict)),
                ("deployment_config", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "model_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hardware_profiles",
                        to="hardware_orch.modelprofile",
                    ),
                ),
            ],
        ),
    ]
