# Generated by Codex on 2026-05-20

import django.conf
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(django.conf.settings.AUTH_USER_MODEL),
        ("hardware_orch", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("family", models.CharField(default="llm", max_length=64)),
                ("image", models.CharField(max_length=512)),
                ("context", models.CharField(max_length=512)),
                ("dockerfile", models.CharField(max_length=512)),
                ("internal_port", models.PositiveIntegerField(default=8000)),
                ("health_path", models.CharField(default="/health", max_length=255)),
                ("env", models.JSONField(blank=True, default=dict)),
                ("endpoints", models.JSONField(blank=True, default=list)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="ModelImageDeployment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("local-docker", "Local Docker"),
                            ("kubernetes", "Kubernetes"),
                            ("aws-ecs", "AWS ECS"),
                            ("gcp-cloud-run", "GCP Cloud Run"),
                        ],
                        default="local-docker",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("deploying", "Deploying"),
                            ("running", "Running"),
                            ("destroying", "Destroying"),
                            ("destroyed", "Destroyed"),
                            ("failed", "Failed"),
                        ],
                        default="planned",
                        max_length=32,
                    ),
                ),
                ("service_name", models.CharField(max_length=255)),
                ("host_port", models.PositiveIntegerField(blank=True, null=True)),
                ("public_host", models.CharField(default="http://localhost", max_length=512)),
                ("runtime", models.JSONField(blank=True, default=dict)),
                ("routes", models.JSONField(blank=True, default=list)),
                ("provider_resource_id", models.CharField(blank=True, max_length=512)),
                ("quota", models.JSONField(blank=True, default=dict)),
                ("billing", models.JSONField(blank=True, default=dict)),
                ("iam", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "model_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deployments",
                        to="hardware_orch.modelimage",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_image_deployments",
                        to=django.conf.settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["owner", "status"], name="hardware_or_owner_i_c949f3_idx"),
                    models.Index(fields=["provider", "status"], name="hardware_or_provide_43cdc6_idx"),
                    models.Index(fields=["host_port"], name="hardware_or_host_po_4abf21_idx"),
                ],
            },
        ),
    ]
