# Generated by Django 6.0.4 on 2026-04-21 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TutorialTag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=80, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="Tutorial",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("excerpt", models.TextField(blank=True, default="")),
                ("body_markdown", models.TextField()),
                ("cover_image_path", models.CharField(blank=True, default="", max_length=1024)),
                ("cover_image_url", models.URLField(blank=True, default="")),
                ("cover_image_alt", models.CharField(blank=True, default="", max_length=255)),
                ("thumbnail_image_path", models.CharField(blank=True, default="", max_length=1024)),
                ("thumbnail_image_url", models.URLField(blank=True, default="")),
                ("status", models.CharField(choices=[("draft", "Draft"), ("published", "Published"), ("archived", "Archived")], default="draft", max_length=20)),
                ("auto_tags", models.JSONField(blank=True, default=list)),
                ("seo_title", models.CharField(blank=True, default="", max_length=70)),
                ("meta_description", models.CharField(blank=True, default="", max_length=160)),
                ("seo_keywords", models.CharField(blank=True, default="", max_length=255)),
                ("revision_number", models.PositiveIntegerField(default=1)),
                ("read_time_minutes", models.PositiveIntegerField(default=1)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("last_revised_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("author", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tutorials", to=settings.AUTH_USER_MODEL)),
                ("tags", models.ManyToManyField(blank=True, related_name="tutorials", to="tutorials.tutorialtag")),
            ],
            options={"ordering": ["-published_at", "-updated_at", "-id"]},
        ),
    ]

